//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUrenRegistratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class hourRegistration
    {
        public int hourId { get; set; }
        public int userTaskId { get; set; }
        public int userId { get; set; }
        public int taskId { get; set; }
        public int projectId { get; set; }
        public System.DateTime date { get; set; }
        public string responsibilty { get; set; }
        public Nullable<int> numberOfHours { get; set; }
    
        public virtual UserTask UserTask { get; set; }
    }
}
