//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUrenRegistratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.tasks = new HashSet<task>();
            this.UserTasks = new HashSet<UserTask>();
        }
    
        public int projectId { get; set; }
        public string projectName { get; set; }
        public string projectDescription { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool locked { get; set; }
    
        public virtual ICollection<task> tasks { get; set; }
        public virtual ICollection<UserTask> UserTasks { get; set; }
    }
}
