//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUrenRegistratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserTasks = new HashSet<UserTask>();
        }
    
        public int userId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string passwrd { get; set; }
        public bool permission { get; set; }
        public string photo { get; set; }
        public Nullable<bool> wachtwoordReset { get; set; }
    
        public virtual ICollection<UserTask> UserTasks { get; set; }
    }
}
